### PR TITLE
performance: introduced buf.Pool which helps reuse memory buffers

### LINKED ISSUE #93: High memory usage seen with a large number of small files
I created a 5 test directories (on an NVME device) with 2M files each. 100 bytes of random data in each one of those files.

```
$ kopia repository create s3 --bucket=<test-bucket> --prefix=kopia/
$ time kopia snapshot create /mnt/ssd/smallfiles
...

real	13m36.700s
user	72m46.181s
sys	5m23.254s
```

I found the memory usage to be quite high. See `pidstat` below but I saw it grow to ~21GB on one of these runs.
```
$ pidstat -r -p 5049 1
Linux 4.15.0-1044-aws (ip-172-31-10-90) 	08/24/19 	_x86_64_	(16 CPU)

04:13:01      UID       PID  minflt/s  majflt/s     VSZ     RSS   %MEM  Command
04:13:02     1000      5049     36.00      0.00 16696284 15266768  47.87  kopia
...
```

Dataset Generation Script (not my own but found elsewhere):
```python
!/usr/bin/env python3
import os
import sys
import argparse
from multiprocessing import Pool
from functools import partial


def create_files(args, i):
    path = os.path.join(args.path, 'my-dir-name-%d' % i)
    os.mkdir(path)
    for j in range(args.filenum):
        with open(os.path.join(path, 'my-random-file-%d.data' % j), 'wb') as f:
            f.write(os.urandom(args.filesize))


def main(argv):
    parser = argparse.ArgumentParser(description='Create directories and files for backup test')
    parser.add_argument('-p', '--path', type=str, required=True, help='Path to the directory')
    parser.add_argument('-d', '--dirnum', type=int, required=True, help='Number of subdirectories')
    parser.add_argument('-f', '--filenum', type=int, required=True, help='Number of files per directory')
    parser.add_argument('-s', '--filesize', type=int, required=True, help='File size')
    args = parser.parse_args()

    if os.path.exists(args.path):
        print('ERROR: destination directory %s already exists' % args.path, file=sys.stderr)
        return 1
    elif not os.path.exists(os.path.dirname(args.path)):
        print('ERROR: parent directory for destination %s does not exist' % args.path, file=sys.stderr)
        return 1

    os.mkdir(args.path)
    with Pool(min(args.dirnum, 8)) as p:
        p.map(partial(create_files, args), range(args.dirnum))


if __name__ == '__main__':
    sys.exit(main(sys.argv))
```

and I then ran
```
python3 files.py -d 5 -f 2000000 -s 100 -p /mnt/ssd/smallfiles
```

### LINKED ISSUE #125: Investigate memory usage during snapshot of 100GB+ tree
Follow up to #93 

The setup is:
* 100K files (single directory)
* Each file is 1MB.

Then create a snapshot of this directory.

* Multi-GB RSS (1-8GB) was observed in a few initial runs.
* Running with memory profiling enabled results in RSS ~ 0.5GB.

### PR DESCRIPTION
**Pull request by jkowalski**
content manager:

Previously we would store special field Payload for contents
that were added but never flushed to the store and it was not
encrypted. This required special handling different for pending
vs flushed contents.

This change maintains pending pack buffer ready to be flushed
and appends encrypted contents to it, which avoids data copying.
The buffers are pooled to avoid allocations.

This change also introduces 'buf.Pool', which allows efficient management of ephemeral in-memory buffer using multiple buffers.

## Impact of this PR:

```
10 GB: 10 dirs x 10 files x 100 mb each:

before: time=50.152      cpu=372.200      memory=824.699     vmem=5841.207
after:  time=45.133      cpu=200.400      memory=725.645     vmem=5659.527

10 GB: 10 dirs x 10000 files x 100 kb each:

before: time=43.130      cpu=545.600      memory=656.676     vmem=5724.605
after:  time=43.108      cpu=603.400      memory=407.422     vmem=5392.953

100 MB: 100 directories x 10000 files x 100 bytes each:

before: time=108.431     cpu=149.100      memory=834.781     vmem=5825.094
after:  time=54.108      cpu=100.000      memory=696.168    vmem= 5747.988
```

Fixes #125
Fixes #93

### CODE REVIEW

File: internal/buf/pool.go [hunk 1]
```diff
@@ -0,0 +1,205 @@
...
+		}
+
+		// add one more segment up to specified limit
+		if p.InitializeSegments(1) {
+			continue
+		}
+
+		// wait until some segment becomes free or some time passes, whichever comes first
+		select {
+		case <-p.segmentReleased:
```
Comment (julio-lopez) [inline internal/buf/pool.go]: If this is a frequent code path and `<-p.segmentReleased` is a more frequent case than the one below, this ends up allocating many timers that are not released until the timer fires. Now, this may not make a difference given the `allocationRetryTimeout` and GC frequency.

File: internal/buf/pool.go [hunk 2]
```diff
@@ -0,0 +1,205 @@
...
+	notify := false
+
+	// best effort compare-and-swap, which will pop the buffer off the stack in its appropriate segment
+	if atomic.CompareAndSwapInt32(&b.segment.nextUnallocated, b.nextUnallocated, b.previousNextUnallocated) {
+		// popped from the stack in the segment
+		notify = true
+	}
+
+	if atomic.AddInt32(&b.segment.allocatedBufCount, -1) == 0 {
+		// last allocated Buf, we can reset 'next' to zero
```
Comment (julio-lopez) [inline internal/buf/pool.go]: I think there's a race here.
- Suppose the case where this is the last `Buf` in this segment.
- The last `Release` executes up to the line above, but not line 52.

In the mean time an allocate on the same same segment executes up to line 81, but not 82.
At this point `s.nextUnallocated` is after the `Buf.data` for this allocation

When 52 executes, it would reset `s.nextUnallocated` to 0 and it would corrupt the segment and subsequent allocations on the same segment.

**Comment by julio-lopez** [comment]
@jkowalski I think that we should be able to merge all the patches that are not related to `buf.Pool` now, and then merge `buf.Pool` related patches separately. WDYT?

File: internal/buf/pool.go [hunk 3]
```diff
@@ -0,0 +1,205 @@
...
+		n = remaining
+	}
+
+	if n == 0 {
+		return false
+	}
+
+	var newSegments []*segment
+
+	newSegments = append(newSegments, p.segments...)
```
[the remark this answers is not in the document]
Comment (jkowalski) [reply internal/buf/pool.go]: i removed maxSegments in the latest version. Unless there's a `Buf` leak, this should not be needed.

File: internal/buf/pool.go [hunk 4]
```diff
@@ -0,0 +1,205 @@
...
+			pool: p,
+		})
+	}
+
+	p.segments = newSegments
+
+	return true
+}
+
+// Allocate allocates a slice of the buffer
```
[the remark this answers is not in the document]
Comment (jkowalski) [reply internal/buf/pool.go]: done

File: internal/buf/pool.go [hunk 5]
```diff
@@ -0,0 +1,205 @@
...
+func (p *Pool) Allocate(n int) Buf {
+	// requested more than the pool can cache, allocate throw-away buffer.
+	if p == nil || n > p.segmentSize {
+		return Buf{0, 0, make([]byte, n), nil}
```
[the remark this answers is not in the document]
Comment (jkowalski) [reply internal/buf/pool.go]: added instrumentation

File: internal/buf/pool.go (hunk 1 above)
Comment (jkowalski) [reply internal/buf/pool.go]: removed this whole channel business, we can simply add more segments

File: internal/buf/pool.go (hunk 2 above)
Comment (jkowalski) [reply internal/buf/pool.go]: fixed by adding mutex and removing atomic

File: internal/buf/pool.go [hunk 6]
```diff
@@ -0,0 +1,205 @@
...
+		}
+	}
+}
+
+// Pool manages allocations of short-term data buffers from a pool.
+//
+// Note that buffers managed by the pool are meant to be extremely short lived and are suitable
+// for in-memory operations, such as encryption, compression, etc, but not for I/O buffers of any kind.
+// It is EXTREMELY important to always release memory allocated from the Pool. Failure to do so will
+// result in
```
[the remark this answers is not in the document]
Comment (jkowalski) [reply internal/buf/pool.go]: done

File: internal/buf/pool.go [hunk 7]
```diff
@@ -39,59 +39,61 @@ func (b *Buf) Release() {
...
-		if atomic.CompareAndSwapInt32(&s.nextUnallocated, v, v+n) {
-			atomic.AddInt32(&s.allocatedBufCount, 1)
+	// we likely have space, allocate under exclusive lock
+	s.mu.Lock()
+	defer s.mu.Unlock()
 
-			return Buf{v + n, v, s.data[v : v+n : v+n], s}, true
-		}
+	// see if we have capacity in this segment
+	v := s.nextUnallocated
```
Comment (julio-lopez) [inline internal/buf/pool.go]: nit: maybe rename `v` to `nu` or `next` or even `prev`? Not sure what would make it clearer.

File: internal/buf/pool.go [hunk 8]
```diff
@@ -39,59 +39,61 @@ func (b *Buf) Release() {
...
+
+	if v+n > len(s.data) {
+		// out of space in this segment
+		return Buf{}, false
 	}
+
+	s.allocatedBufCount++
+	s.nextUnallocated += n
+
+	return Buf{s.data[v : v+n : v+n], v + n, v, s}, true
```
Comment (julio-lopez) [inline internal/buf/pool.go]: use named initializers for `Buf` ?

File: internal/buf/pool.go [hunk 9]
```diff
@@ -107,26 +109,71 @@ func (s *segment) allocate(count int) (Buf, bool) {
...
+
 	return p
 }
 
+// Close closes the pool
+func (p *Pool) Close() {
+	close(p.closed)
+}
+
+func (p *Pool) reportMetrics() {
```
Comment (julio-lopez) [inline internal/buf/pool.go]: nit: pass the `Context` from the caller (go routine above)?

File: internal/buf/pool.go [hunk 10]
```diff
@@ -188,18 +227,7 @@ func (p *Pool) Allocate(n int) Buf {
...
-			continue
-		}
-
-		// wait until some segment becomes free or some time passes, whichever comes first
-		select {
-		case <-p.segmentReleased:
-		case <-time.After(allocationRetryTimeout):
-		}
+		// add one more segment
+		p.AddSegments(1)
```
Comment (julio-lopez) [inline internal/buf/pool.go]: As discussed earlier, a concern here is that there should be a way of freeing up _excess_ segments as they become empty. Perhaps keep a minimum number of segments in the pool, but releasing extra unused segments. Or perhaps having a maximum number of unused segments that can be kept around. Thoughts?

Related to this, it'd be good to track the number of unused / empty segments. That is, on `Release` increment a counter of unused segments when the allocated buffer count reaches 0, or when a segment is initially created. Decrease the counter on allocate when allocating from a currently empty segment.

Comment (jkowalski) [reply internal/buf/pool.go]: good ideas, will do in separate PR

File: internal/buf/pool.go (hunk 7 above)
Comment (jkowalski) [reply internal/buf/pool.go]: done

File: internal/buf/pool.go (hunk 9 above)
Comment (jkowalski) [reply internal/buf/pool.go]: done

File: internal/buf/pool.go (hunk 8 above)
Comment (jkowalski) [reply internal/buf/pool.go]: done
