### PR TITLE
fix(general): serialize empty `Manifest.Stats` field

### LINKED ISSUE #5006: Starting kopiaui only prints the version
My sister (macos) has this weird interface when we open a connected repository:

Image

Any idea what's going on here? We can't do anything now… Kopia 0.22.0

### PR DESCRIPTION
**Pull request by julio-lopez**
- Fixes #5006

### CODE REVIEW

**Comment by julio-lopez** [comment]
- See [#5006#issuecomment-3567627991](https://github.com/kopia/kopia/issues/5006#issuecomment-3567627991)

File: snapshot/manifest.go [hunk 1]
```diff
@@ -23,7 +23,7 @@ type Manifest struct {
 	StartTime   fs.UTCTimestamp `json:"startTime"`
 	EndTime     fs.UTCTimestamp `json:"endTime"`
 
-	Stats            Stats  `json:"stats,omitzero"`
+	Stats            Stats  `json:"stats"`
```
Comment (julio-lopez) [inline snapshot/manifest.go:26]: Temporary fix, the proper fix should be in the UI.
