### PR TITLE
Fixed symlink restore behavior on macOS

### LINKED ISSUE #672: kopia restore symlink issue on MacOS
Hello.

I tried to restored symlinks lying inside the backup repository and it failed on MacOS Catalina 10.15.7 with `no such file or directory` error.

Here is the the set of commands to reproduce it.

```bash
$ kopia repository create filesystem --path /tmp/backup_repo

$ mkdir -p /tmp/backup/test{1,2,3}/testdir

$ ln -s ../../test3 /tmp/backup/test1/testdir/link

$ tree /tmp/backup
/tmp/backup
├── test1
│   └── testdir
│       └── link -> ../../test3
├── test2
│   └── testdir
└── test3
    └── testdir

$ kopia snapshot create /tmp/backup

$ kopia snapshot list

$ kopia ls -l -r k06e1433e6df307edbf5300202100fbc9
drwxr-xr-x            0 0001-01-01 00:57:44 LMT kb617b7e13f49f51461cd3951dd3cd752  test1/
drwxr-xr-x            0 0001-01-01 00:57:44 LMT k307395a5fe1138be2289c147994a5aa9  test1/testdir/
Lrwxr-xr-x           11 2020-10-07 19:49:35 CEST 9feaa8ce717e3c70e8846517b914e4a9   test1/testdir/link
drwxr-xr-x            0 2020-10-07 19:49:35 CEST ka23b80b83a462dc224022c3511fb5878  test2/
drwxr-xr-x            0 2020-10-07 19:49:35 CEST kaab8eb811a8bce8f803d4c005487a639  test2/testdir/
drwxr-xr-x            0 2020-10-07 19:49:35 CEST kbaa6da0a2a4aa20b6452c27229d60880  test3/
drwxr-xr-x            0 2020-10-07 19:49:35 CEST k5f8d2c8b98a8e3ce0b075e3590f47138  test3/testdir/

$ kopia restore k06e1433e6df307edbf5300202100fbc9 --log-level=debug ~/test-restore/
19:51:30.901 [kopia/cli] build version v0.7.2, available v
19:51:30.902 [kopia/cli] no updated version available
19:51:30.934 [kopia/repo] password for /Users/petr_ruzicka/Library/Application Support/kopia/repository.config retrieved from OS keyring
Restoring to local filesystem (/Users/petr_ruzicka/test-restore/)...
19:51:31.125 [kopia/manifest] listing manifest contents
19:51:31.127 [restore] dir: ''
19:51:31.128 [restore] dir: 'test1'
19:51:31.128 [restore] dir: 'test1/testdir'
19:51:31.129 [restore] symlink: 'test1/testdir/link'
19:51:31.130 [kopia/cli] [STORAGE] GetBlob("p57e0e6f047673e9f39fb801c5dba5627",754,39)=({39 bytes}, <nil>) took 470.541µs
19:51:31.131 [restore] CreateSymlink /Users/petr_ruzicka/test-restore/test1/testdir/link => ../../test3
19:51:31.132 [kopia/cli] [STORAGE] GetBlob("kopia.maintenance",0,-1)=({514 bytes}, <nil>) took 436.378µs
19:51:31.132 [maintenance] full manintenance cycle not enabled
19:51:31.132 [maintenance] not due for quick manintenance cycle until 2020-10-07 20:49:36.06471 +0200 CEST
19:51:31.132 [maintenance] not due for maintenance
19:51:31.132 [kopia/cli] [STORAGE] Close()=<nil> took 288ns
19:51:31.133 [kopia/memory] in use heap 2629632 (delta 2629632 max 0) stack 589824 (delta 589824 max 0)
kopia: error: error copying: copy directory contents: copy directory contents: copy directory contents: error setting attributes: could not change owner/group for /Users/petr_ruzicka/test-restore/test1/testdir/link: chown /Users/petr_ruzicka/test-restore/test1/testdir/link: no such file or directory, try --help
```

I'm not sure if this is a problem of MacOS only or if it's also in other OS. Can somebody confirm it in MacOS / Linux / ... ?
(just wanted to be sure it's not related only to my environment)

Thank you

### PR DESCRIPTION
**Pull request by jkowalski**
On macOS (unlike Linux and Windows) symbolic links can have separate owners and attributes and to set them on restore we need to use different APIs, otherwise we'd be trying to modify the properties of target and not the link itself and if the link points to a non-existing file/dir we would fail with not found.

Fixes #672

### CODE REVIEW

File: snapshot/snapshotfs/upload.go [hunk 1]
```diff
@@ -479,16 +479,19 @@ func (b *dirManifestBuilder) addEntry(de *snapshot.DirEntry) {
 
 	b.entries = append(b.entries, de)
 
+	if de.ModTime.After(b.summary.MaxModTime) {
```
Comment (julio-lopez) [inline snapshot/snapshotfs/upload.go:482]: Does this affect deduplication of entire directories?

**Review by julio-lopez — COMMENTED** [review]
👍 LG +1
