### PR TITLE
feat(cli): implementation for 'kopia snapshot fix'

### LINKED ISSUE #799: feature: implement ability to remove objects and their references after snapshot
There are some scenarios where you may want to get rid of objects (and their references) after they have been snapshotted in the repository:

- you accidentally snapshot a very large file or directory that should have been excluded
- you accidentally snapshot a sensitive file (say containing passwords, etc.)
- repository blobs got damaged and you want to remove references to them from manifests and directory listings.

I propose we add a feature to purge objects, say:

```
$ kopia purge <object-id>
```

This would:

- scan all snapshot roots
- recursively rewrite all directory listings, eliminating entries that had references to the objects to be removed to exclude them
- rewrite snapshots manifests whose object IDs have changed

The contents containing old object will become orphaned and subject to next GC.

Assuming `q` blobs are cached, this actually should be reasonably quick.

More ideas:

```
$ kopia drop-ignored
```

This would re-run old snapshots but apply current ignore rules (similar to migration in-place)

```
$ kopia snapshot verify --fix-unreadable
```

This would automatically rewrite directories to eliminate references to any objects for which the blobs are missing during snapshot verification.

### PR DESCRIPTION
**Pull request by jkowalski**
feat(cli): implementation for 'kopia snapshot fix'

This allows modifications and fixes to the snapshots after they have
been taken.

Supported are:

* `kopia snapshot fix remove-invalid-files [--verify-files-percent=X]`

Removes all directory entries where the underlying files cannot be
read based on index analysis (this does not read the files, only index
structures so is reasonably quick).

`--verify-files-percent=100` can be used to trigger full read for
all files.

* `kopia snapshot fix remove-files --object-id=<object-id>`

Removes the object with a given ID from the entire snapshot tree.
Useful when you accidentally snapshot a sensitive file.

* `kopia snapshot fix remove-files --filename=<wildcard>`

Removes the files with a given name from the entire snapshot tree.
Useful when you accidentally snapshot a sensitive file.

By default all snapshots are analyzed and rewritten. To limit the scope
use:

```
--source=user@host:/path
--manifest-id=manifestID
```

By default the rewrite operation writes new directory entries but
does not replace the manifests. To do that pass `--commit`.

Related #1906
Fixes #799

### CODE REVIEW

**Comment by jkowalski** [comment]
This is not complete yet, needs testing, sending out early to get feedback on the CLI.

File: cli/command_snapshot_fix.go [hunk 1]
```diff
@@ -0,0 +1,188 @@
...
+	verifier *snapshotfs.Verifier
+}
+
+func (c *commandSnapshotFix) setup(svc appServices, parent commandParent) {
+	cmd := parent.Command("fix", "Fix snapshot consistency issues")
+
+	// action to perform
+	cmd.Flag("remove-invalid-files", "Delete invalid files").BoolVar(&c.removeInvalidFiles)
+	cmd.Flag("remove-object", "Remove objects with specified ID").StringsVar(&c.removeObjectIDs)
+	cmd.Flag("remove-file", "Remove file with specified name (unqualified)").StringsVar(&c.removeFilesByName)
```
Comment (adowair) [inline cli/command_snapshot_fix.go:36]: Since these are mutually exclusive in usage (or I imagine so), can we make them subcommands rather than flags?

```shell
kopia snapshot fix remove-invalid-files
kopia snapshot fix remove-object
kopia snapshot fix remove-file
```

What do you think?

File: cli/command_snapshot_fix.go [hunk 2]
```diff
@@ -0,0 +1,188 @@
...
+
+	// scope of rewrite
+	cmd.Flag("manifest-id", "Manifest IDs").StringsVar(&c.manifestIDs)
+	cmd.Flag("source", "Source to target (username@hostname:/path)").StringsVar(&c.sources)
+
+	// verification options
+	cmd.Flag("full-read", "Perform full read when verifying files").BoolVar(&c.fullRead)
+
+	cmd.Flag("commit", "Update snapshot manifests").BoolVar(&c.commit)
```
Comment (adowair) [inline cli/command_snapshot_fix.go:45]: Forgive my ignorance: what is the point of having this default to off?

File: cli/command_snapshot_fix.go [hunk 3]
```diff
@@ -0,0 +1,188 @@
...
+	}
+
+	for _, n := range c.removeFilesByName {
+		if ent.Name == n {
+			return nil, nil
+		}
+	}
+
+	if c.verifier != nil {
+		fname := dirRelativePath + "/" + ent.Name
```
Comment (adowair) [inline cli/command_snapshot_fix.go:64]: tiny nit:
```suggestion
		fname := filepath.Join(dirRelativePath, ent.Name)
```

**Review by adowair — COMMENTED** [review]
Nice! initial thoughts

- If we run this commands once without `--commit`, then once with, will there be duplicated work?

File: cli/command_snapshot_fix.go (hunk 3 above)
Comment (jkowalski) [reply cli/command_snapshot_fix.go:64]: FWIW this is actually subtly different (not sure if that matters), on Windows it will use `\` even for Unix snapshots. and `/` and `\` are both supported on Windows, although slash looks a bit out of place.

File: cli/command_snapshot_fix.go [hunk 4]
```diff
@@ -0,0 +1,188 @@
...
+		}
+	}
+
+	return ent, nil
+}
+
+func (c *commandSnapshotFix) run(ctx context.Context, rep repo.RepositoryWriter) error {
+	rw := snapshotfs.NewDirRewriter(rep, c.rewriteEntries)
+
+	if c.removeInvalidFiles {
```
Comment (Shrekster) [inline cli/command_snapshot_fix.go:79]: Might be good idea to also specify a dr-run flag to not actually perform repo changes, instead just log them.

File: cli/command_snapshot_fix.go (hunk 1 above)
Comment (jkowalski) [reply cli/command_snapshot_fix.go]: That's a great idea. I implemented something very similar, PTAL.

File: cli/command_snapshot_fix.go (hunk 2 above)
Comment (jkowalski) [reply cli/command_snapshot_fix.go:38]: Safety, mostly. If the `fix` ends up deleting the entire repository (because of some broad deletion rule), that's not really helpful.

File: cli/command_snapshot_fix.go (hunk 4 above)
Comment (jkowalski) [reply cli/command_snapshot_fix.go]: That's the idea behind `--commit` flag.

**Review by adowair — COMMENTED** [review]
This is great @jkowalski , I've left some cosmetic suggestions

File: cli/command_snapshot_fix_invalid_files.go [hunk 5]
```diff
@@ -0,0 +1,59 @@
...
+func (c *commandSnapshotFixInvalidFiles) setup(svc appServices, parent commandParent) {
+	cmd := parent.Command("remove-invalid-files", "Remove references to invalid (unreadable) files in snapshots.")
+	c.common.setup(svc, cmd)
+
+	cmd.Flag("verify-files-percent", "Verify a percentage of files by fully downloading them [0.0 .. 100.0]").Default("0").Float64Var(&c.verifyFilesPercent)
+
+	cmd.Action(svc.repositoryWriterAction(c.run))
+}
+
+func (c *commandSnapshotFixInvalidFiles) rewriteEntries(ctx context.Context, dirRelativePath string, ent *snapshot.DirEntry) (*snapshot.DirEntry, error) {
```
[the remark this answers is not in the document]
Comment (jkowalski) [reply cli/command_snapshot_fix_invalid_files.go]: yes, renamed, the function has gotten more advanced and is not really about skipping anymore. PTAL

File: cli/command_snapshot_fix.go [hunk 6]
```diff
@@ -0,0 +1,133 @@
...
+				man.ID,
+				old.RootEntry.ObjectID,
+				man.RootEntry.ObjectID)
+
+			fixed = true
+		}
+	}
+
+	if fixed && !c.commit {
+		return errors.Errorf("fixes made, but not committed, pass --commit to update snapshots")
```
[the remark this answers is not in the document]
Comment (jkowalski) [reply cli/command_snapshot_fix.go]: done

File: cli/command_snapshot_fix_remove_files.go [hunk 7]
```diff
@@ -0,0 +1,57 @@
...
+	cmd := parent.Command("remove-files", "Remove references to files from snapshots.")
+	c.common.setup(svc, cmd)
+
+	cmd.Flag("object-id", "Remove files by their object ID").StringsVar(&c.removeObjectIDs)
+	cmd.Flag("filename", "Remove files by filename (wildcards are supported)").StringsVar(&c.removeFilesByName)
+
+	cmd.Action(svc.repositoryWriterAction(c.run))
+}
+
+func (c *commandSnapshotFixRemoveFiles) rewriteEntries(ctx context.Context, dirRelativePath string, ent *snapshot.DirEntry) (*snapshot.DirEntry, error) {
```
[the remark this answers is not in the document]
Comment (jkowalski) [reply cli/command_snapshot_fix_remove_files.go]: done

File: cli/command_snapshot_fix_invalid_files.go [hunk 8]
```diff
@@ -0,0 +1,59 @@
...
+
+type commandSnapshotFixInvalidFiles struct {
+	common commonRewriteSnapshots
+
+	verifyFilesPercent float64
+	verifier           *snapshotfs.Verifier
+}
+
+func (c *commandSnapshotFixInvalidFiles) setup(svc appServices, parent commandParent) {
+	cmd := parent.Command("remove-invalid-files", "Remove references to invalid (unreadable) files in snapshots.")
```
[the remark this answers is not in the document]
Comment (jkowalski) [reply cli/command_snapshot_fix_invalid_files.go]: done

**Review by adowair — COMMENTED** [review]
Thank you Jarek, looks good to me, with a couple of notes:

**Review by Shrekster — APPROVED** [review]
Looks good. Thank you@

File: cli/command_snapshot_fix_remove_files.go [hunk 9]
```diff
@@ -0,0 +1,59 @@
...
+	cmd.Flag("object-id", "Remove files by their object ID").StringsVar(&c.removeObjectIDs)
+	cmd.Flag("filename", "Remove files by filename (wildcards are supported)").StringsVar(&c.removeFilesByName)
+
+	cmd.Action(svc.repositoryWriterAction(c.run))
+}
+
+func (c *commandSnapshotFixRemoveFiles) rewriteEntry(ctx context.Context, dirRelativePath string, ent *snapshot.DirEntry) (*snapshot.DirEntry, error) {
+	for _, id := range c.removeObjectIDs {
+		if string(ent.ObjectID) == id {
+			return nil, nil
```
[the remark this answers is not in the document]
Comment (jkowalski) [reply cli/command_snapshot_fix_remove_files.go:35]: done
