### PR TITLE
Ignore read errors based on policy settings

### LINKED ISSUE #177: kopia server: automatic snapshots not created
I have set up kopia server to back up a few directories each night. Most of the time, this succeeds but occasionally kopia will not have sufficient permissions to access one or two sub-directories of a directory to back up.

When running `kopia snapshot create /var/data/` manually, the directories are skipping and the snapshot is created anyway, e.g.

```
12:11:13.381 [kopia/upload] unable to hash file "./postgres/pg_stat_tmp/db_0.stat": unable to open file: open /var/data/postgres/pg_stat_tmp/db_0.stat: permission denied, ignoring
12:11:13.381 [kopia/upload] unable to hash file "./postgres/pg_stat_tmp/db_1.stat": unable to open file: open /var/data/postgres/pg_stat_tmp/db_1.stat: permission denied, ignoring
12:11:13.381 [kopia/upload] unable to hash file "./postgres/pg_stat_tmp/db_13067.stat": unable to open file: open /var/data/postgres/pg_stat_tmp/db_13067.stat: permission denied, ignoring
12:11:13.381 [kopia/upload] unable to hash file "./postgres/pg_stat_tmp/db_16384.stat": unable to open file: open /var/data/postgres/pg_stat_tmp/db_16384.stat: permission denied, ignoring
12:11:13.381 [kopia/upload] unable to hash file "./postgres/pg_stat_tmp/db_16386.stat": unable to open file: open /var/data/postgres/pg_stat_tmp/db_16386.stat: permission denied, ignoring
12:11:13.381 [kopia/upload] unable to hash file "./postgres/pg_stat_tmp/db_16388.stat": unable to open file: open /var/data/postgres/pg_stat_tmp/db_16388.stat: permission denied, ignoring
12:11:13.381 [kopia/upload] unable to hash file "./postgres/pg_stat_tmp/db_16516.stat": unable to open file: open /var/data/postgres/pg_stat_tmp/db_16516.stat: permission denied, ignoring
12:11:13.381 [kopia/upload] unable to hash file "./postgres/pg_stat_tmp/db_17183.stat": unable to open file: open /var/data/postgres/pg_stat_tmp/db_17183.stat: permission denied, ignoring
12:11:13.381 [kopia/upload] unable to hash file "./postgres/pg_stat_tmp/db_18529.stat": unable to open file: open /var/data/postgres/pg_stat_tmp/db_18529.stat: permission denied, ignoring
12:11:13.381 [kopia/upload] unable to hash file "./postgres/pg_stat_tmp/db_24972.stat": unable to open file: open /var/data/postgres/pg_stat_tmp/db_24972.stat: permission denied, ignoring
12:11:13.381 [kopia/upload] unable to hash file "./postgres/pg_stat_tmp/global.stat": unable to open file: open /var/data/postgres/pg_stat_tmp/global.stat: permission denied, ignoring
```

For the automatic snapshot to be created by the server, an upload error occurs instead. From the output is appears that some chunks are uploaded, but no actual snapshot is created (`kopia snapshot list` shows no entries).

```
[...]
Jan 26 03:00:19 h2594255 kopia[19861]: 03:00:19.726 [kopia/cli] processing upload 'pb6a88a0c30adeb5cb815e98b7722bf01' 21.3 MB of 22.8 MB (93%)#033[0m
Jan 26 03:00:19 h2594255 kopia[19861]: 03:00:19.847 [kopia/cli] processing upload 'pb6a88a0c30adeb5cb815e98b7722bf01' 22.3 MB of 22.8 MB (97%)#033[0m
Jan 26 03:00:20 h2594255 kopia[19861]: #033[32m03:00:20.612 [kopia/cli] completed upload 'pb6a88a0c30adeb5cb815e98b7722bf01' 22.8 MB#033[0m
Jan 28 03:01:02 h2594255 kopia[19861]: #033[31m03:01:02.364 [kopia/server] upload error: unable to process directory "influxdb": unable to process directory "wal": unable to process directory "_internal":
 unable to process directory "monitor": unable to process directory "15": open /var/data/influxdb/wal/_internal/monitor/15: permission denied#033[0m
[...]
```

There appears to be a lot of unused or unreferenced objects:

```
$ kopia snapshot gc
12:18:31.362 [kopia/snapshot/gc] looking for active contents
12:18:31.363 [kopia/upload] processed(0/6) active 1
12:18:32.029 [kopia/snapshot/gc] looking for unreferenced contents
12:18:32.047 [kopia/snapshot/gc] found 123 unused contents (103.5 MiB bytes)
12:18:32.047 [kopia/snapshot/gc] found 31 unused contents that are too recent to delete (12.8 MiB bytes)
12:18:32.047 [kopia/snapshot/gc] found 4310 in-use contents (6.2 GiB bytes)
12:18:32.047 [kopia/snapshot/gc] found 3 in-use system-contents (3.5 KiB bytes)
```

Is there any chance to force kopia to create automatic snapshots even if some directories are not accessible?

### PR DESCRIPTION
**Pull request by redgoat650**
Added an error handling policy section. Can independently control error handling for directory and file read errors, toggle-able from the `policy set` command to either "true", "false", or "inherit". If any read error is hit, the error handling will check the effective policy on whether to ignore it or not. Currently there is no differentiation between read error types, though in the future we may want to add the `errors.Is(err, os.ErrPermission)` conditional.

Fix was implemented such that the policy ignores read errors ONLY on child entries of the source. So a snapshot will still fail if the source root directory itself can't be read, but you can ignore the error if a file or a subdirectory in the snapshot source root can't be read. I did this to address some otherwise strange behavior where you would successfully snapshot (because you ignored the error), but couldn't restore that snapshot because nothing really happened during the operation.

Fixes #177

### CODE REVIEW

**Comment by julio-lopez** [comment]
@jkowalski PTAL

File: snapshot/policy/error_handling_policy.go [hunk 1]
```diff
@@ -0,0 +1,37 @@
+package policy
+
+// ErrorHandlingPolicy controls error hadnling behavior when taking snapshots.
+type ErrorHandlingPolicy struct {
+	// IgnoreFileErrors controls whether or not snapshot operation should terminate when a file throws an error on being read
+	IgnoreFileErrors bool `json:"ignoreFileErrs,omitempty"`
```
Comment (jkowalski) [inline snapshot/policy/error_handling_policy.go]: why not spell out "Errors" instead of "Errs" ?

File: snapshot/policy/error_handling_policy.go [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+
+	// IgnoreFileErrorSet denotes whether the IgnoreFileErrors bool was actually set in this policy, or if it should be inherited
+	IgnoreFileErrorsSet bool `json:"ignoreFileErrsSet,omitempty"`
```
Comment (jkowalski) [inline snapshot/policy/error_handling_policy.go]: would it be easier to use *bool here to avoid two flags (nil == inherit) ?

Comment (redgoat650) [reply snapshot/policy/error_handling_policy.go]: great call; made the change.
https://github.com/kopia/kopia/pull/207/commits/87b8a11da489dcde0e4ba1ec93e9f4302b930e5b

File: snapshot/policy/error_handling_policy.go (hunk 1 above)
Comment (redgoat650) [reply snapshot/policy/error_handling_policy.go]: ✔️

File: snapshot/snapshotfs/upload.go [hunk 3]
```diff
@@ -663,7 +677,10 @@ func uploadDirInternal(
 		return "", fs.DirectorySummary{}, workItemErr
 	}
 
-	if err := u.processUploadWorkItems(workItems, dirManifest); err != nil && err != errCancelled {
+	errHandlingPolicy := policyTree.EffectivePolicy().ErrorHandlingPolicy
+	ignoreFileErrs := u.IgnoreReadErrors || (errHandlingPolicy.IgnoreFileErrors != nil && *errHandlingPolicy.IgnoreFileErrors)
```
Comment (jkowalski) [inline snapshot/snapshotfs/upload.go]: nit: for readability perhaps add a helper here

u.shouldIgnoreReadErrors(policyTree)

File: tests/testenv/cli_test_env.go [hunk 4]
```diff
@@ -242,7 +242,7 @@ func trimOutput(s string) string {
 
 // ListSnapshotsAndExpectSuccess lists given snapshots and parses the output.
 func (e *CLITest) ListSnapshotsAndExpectSuccess(t *testing.T, targets ...string) []SourceInfo {
-	lines := e.RunAndExpectSuccess(t, append([]string{"snapshot", "list", "-l", "--manifest-id"}, targets...)...)
+	lines := e.RunAndExpectSuccess(t, append([]string{"snapshot", "list", "-l", "--manifest-id", "--max-results", "400"}, targets...)...)
```
Comment (jkowalski) [inline tests/testenv/cli_test_env.go]: why do we need this?

**Comment by jkowalski** [comment]
looks great, few minor comments, feel free to merge

File: tests/testenv/cli_test_env.go (hunk 4 above)
Comment (redgoat650) [reply tests/testenv/cli_test_env.go]: You are right, it's no longer strictly needed. It was added because I originally included `[]string{"false", "true", "inherit"}` for both files and directories in `TestSnapshotFail`. To cut down on test time significantly, I dropped the "inherit" parameter (instead randomly picking "inherit" vs "false" since their behavior is the same) as well as the `0500` permission test cases.

The test checks that the number of expected successful snapshots matches the number reported by `snapshot list` at the end. It was previously failing as the number of snapshots exceeded the `snap list` max size. With these test time improvements, the number of snapshots per source drops to under the default 100 max list size, so yeah this change is no longer strictly necessary.

File: snapshot/snapshotfs/upload.go (hunk 3 above)
Comment (redgoat650) [reply snapshot/snapshotfs/upload.go]: good idea, will add

**Comment by redgoat650** [comment]
Thanks for the review @jkowalski. Changes have been made, please merge at your leisure. I don't have the required permissions to do so myself :)

**Comment by jkowalski** [comment]
(squashed commits into one)
