### PR TITLE
fix(deps-dev): fixup mutex for make check-locks

### LINKED ISSUE #2919: Kopia `make check-locks` fails with `Fault` mutex changes.
The mutex changes to `fault_set.go` did not anticipate support for `gvisor`'s `checklocks` tool.  `make check-locks` will fail once `checklocks` is updated.  `fault_set.go` and possibly `fault.go` need to be modified so `make check-locks` will pass.

### PR DESCRIPTION
**Pull request by aaron-kasten**
Fixes #2919 .

### CODE REVIEW

File: internal/blobtesting/faulty.go [hunk 1]
```diff
@@ -25,13 +25,14 @@ const (
 type FaultyStorage struct {
 	base blob.Storage
 
-	fault.Set
+	*fault.Set
```
Comment (aaron-kasten) [inline internal/blobtesting/faulty.go:28]: lint will complain if the `FaultSet` `mu` is copied for use in `FaultyStorage`.  While the scope of the construction of the `mu` in `FaultSet` does not extend beyond the `NewFaultyStorage` call, a pointer will be used to avoid warnings.

File: internal/fault/fault_set.go [hunk 2]
```diff
@@ -16,25 +16,28 @@ type Method int
...
-func (s *Set) ensureInitialized() {
-	if s.faults == nil {
-		s.faults = map[Method][]*Fault{}
-		s.callCounter = map[Method]int{}
+func NewSet() *Set {
+	q := &Set{
+		mu:          &sync.Mutex{},
+		faults:      map[Method][]*Fault{},
+		callCounter: map[Method]int{},
 	}
```
Comment (aaron-kasten) [inline internal/fault/fault_set.go:31]: Initialize in construction, not lazily.

File: internal/blobtesting/faulty.go (hunk 1 above)
Comment (julio-lopez) [reply internal/blobtesting/faulty.go:28]: Q: would making `mu` a pointer => `*mu` solve the issue as well?

No change requested, mainly curiosity.

**Review by julio-lopez — APPROVED** [review]
+1: LG 👍
Other folks should take a look as well.
