### PR TITLE
Overwrite symlinks with optional flag - fix for #689

### LINKED ISSUE #689: kopia: error: restore error: create symlink: error creating symlink: symlink <relative PATH> <full PATH>: file exists, try --help
When running
kopia snapshot restore and the restore command fails, running it again sometimes fails with this error.

Using MacOS Catalina

### PR DESCRIPTION
**Pull request by redgoat650**
Add symlink overwrite behavior to fix "file exists" error when restoring a symlink that already exists

Before creating the restored symlink, check `os.Lstat`:
- If it returns an error indicating the file does not exist, proceed to symlink creation
- If it returns any other error, propagate the error up to the caller
- If the fileInfo indicates the entry is a symlink AND `--no-overwrite-symlinks` was set in the restore command, propagate an error to the caller
- If `--no-overwrite-symlinks` was NOT set, remove the existing symlink before proceeding to symlink creation
- Else the file exists but it is not of type symlink. Halt the operation and propagate an error indicating we tried to restore a symlink over a file system entry that already existed but was not a symlink.

Added case to `TestSnapshotRestore` that fails before this fix and succeeds after. The case is simply to restore the same snapshot into the same directory twice in a row, where the second restore will be on top of the first one.

Added test case to ensure `--no-overwrite-symlinks` throws an error as expected if restoring into a directory where a symlink already exists at the path symlink creation is attempted.

Added test case to ensure that the restore operation fails if a symlink is needed to be restored to the same path as an existing non-symlink filesystem entry with the same name.

Fixes #689

### CODE REVIEW

**Review by pavannd1 — COMMENTED** [review]
LGTM 👍🏼  Will let Jarek or Julio +2 this.

**Comment by jkowalski** [comment]
Windows build seems to be failing for real (not a flake).

File: cli/command_restore.go [hunk 1]
```diff
@@ -79,6 +80,7 @@ func addRestoreFlags(cmd *kingpin.CmdClause) {
 	cmd.Arg("target-path", "Path of the directory for the contents to be restored").Required().StringVar(&restoreTargetPath)
 	cmd.Flag("overwrite-directories", "Overwrite existing directories").BoolVar(&restoreOverwriteDirectories)
 	cmd.Flag("overwrite-files", "Specifies whether or not to overwrite already existing files").BoolVar(&restoreOverwriteFiles)
+	cmd.Flag("overwrite-symlinks", "Specifies whether or not to overwrite already existing symlinks").BoolVar(&restoreOverwriteSymlinks)
```
Comment (julio-lopez) [inline cli/command_restore.go:83]: It'd be good to document the behavior somewhere in the CLI help. Essentially, a friendlier version of the semantics explained in the PR description.

File: tests/end_to_end_test/restore_test.go [hunk 2]
```diff
@@ -270,19 +276,17 @@ func TestSnapshotRestore(t *testing.T) {
...
 	// Attempt to restore snapshot with an already-existing target directory
 	// It should fail because the directory is not empty
-	_ = os.MkdirAll(restoreFailDir, 0o700)
-
 	e.RunAndExpectFailure(t, "snapshot", "restore", "--no-overwrite-directories", snapID, restoreDir)
 
 	// Attempt to restore snapshot with an already-existing target directory
 	// It should fail because target files already exist
-	_ = os.MkdirAll(restoreFailDir, 0o700)
-
```
Comment (julio-lopez) [inline tests/end_to_end_test/restore_test.go:284]: These seem spurious. Are these changes required? You are probably right that these directory creations are unnecessary, but it makes sense to put them in a separate PR to keep this self-contained.

**Comment by julio-lopez** [comment]
Excerpt of Windows failures:

```
 kopia.exe: error: error restoring: restore error: copy file: error creating directory: cannot replace "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\TestSnapshotRestore774500588\\004\\subdir1\\13cb0051.8363\\4dcc639f1a.8683\\1e663.8944\\c6eb33347902ed9.9015\\e8093ecbc756e.9036\\b56eb.9037" with tempfile "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\TestSnapshotRestore774500588\\004\\subdir1\\13cb0051.8363\\4dcc639f1a.8683\\1e663.8944\\c6eb33347902ed9.9015\\e8093ecbc756e.9036\\b56eb.9037754815188": replace C:\Users\RUNNER~1\AppData\Local\Temp\TestSnapshotRestore774500588\004\subdir1\13cb0051.8363\4dcc639f1a.8683\1e663.8944\c6eb33347902ed9.9015\e8093ecbc756e.9036\b56eb.9037754815188 C:\Users\RUNNER~1\AppData\Local\Temp\TestSnapshotRestore774500588\004\subdir1\13cb0051.8363\4dcc639f1a.8683\1e663.8944\c6eb33347902ed9.9015\e8093ecbc756e.9036\b56eb.9037: Access is denied., try --help
```

https://github.com/kopia/kopia/runs/1697325026?check_suite_focus=true#step:7:8062
```
kopia.exe: error: error restoring: restore error: copy file: error creating directory: cannot replace "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\TestSnapshotRestore774500588\\004\\subdir1\\13cb0051.8363\\4dcc639f1a.8683\\1e663.8944\\c6eb33347902ed9.9015\\e8093ecbc756e.9036\\b56eb.9037" with tempfile "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\TestSnapshotRestore774500588\\004\\subdir1\\13cb0051.8363\\4dcc639f1a.8683\\1e663.8944\\c6eb33347902ed9.9015\\e8093ecbc756e.9036\\b56eb.9037754815188": replace C:\Users\RUNNER~1\AppData\Local\Temp\TestSnapshotRestore774500588\004\subdir1\13cb0051.8363\4dcc639f1a.8683\1e663.8944\c6eb33347902ed9.9015\e8093ecbc756e.9036\b56eb.9037754815188 C:\Users\RUNNER~1\AppData\Local\Temp\TestSnapshotRestore774500588\004\subdir1\13cb0051.8363\4dcc639f1a.8683\1e663.8944\c6eb33347902ed9.9015\e8093ecbc756e.9036\b56eb.9037: Access is denied., try --help
```

`make[1]: *** [Makefile:232: integration-tests] Error 1`

**Comment by redgoat650** [comment]
Failing at the added restore step. Windows doesn't like something about this behavior

File: tests/end_to_end_test/restore_test.go (hunk 2 above)
Comment (redgoat650) [reply tests/end_to_end_test/restore_test.go:284]: To me it makes sense to remove these now. I'm adding a new `--no-overwrite-` case, and my belief is it would be cleaner to have all three cases consistent: three similar test cases back-to-back that all follow the same pattern. The alternatives are (a) either the first two cases follow an unnecessary `mkdir` pattern that the new one doesn't, or (b) we add the new case with the unnecessary pattern for consistency among all three cases (only to be removed later).

If you feel strongly about it I can definitely move them to a separate PR, but IMO the changes aren't as spurious as they might seem.

File: cli/command_restore.go (hunk 1 above)
Comment (redgoat650) [reply cli/command_restore.go:96]: Added a blurb to the restore command help text https://github.com/kopia/kopia/pull/783/commits/75b18876480324cc6258054415651e9ff64c95f1

File: tests/end_to_end_test/restore_test.go [hunk 3]
```diff
@@ -230,6 +230,16 @@ func TestSnapshotRestore(t *testing.T) {
 	// Restored contents should match source
 	compareDirs(t, source, restoreDir)
 
+	// Check restore idempotency. Repeat the restore into the already-restored directory.
+	// If running the test as non-admin on Windows, there may not be sufficient permissions
```
Comment (julio-lopez) [inline tests/end_to_end_test/restore_test.go:234]: @jkowalski thoughts?

**Review by julio-lopez — COMMENTED** [review]
👍 LG +1

@jkowalski should approve though.

**Comment by julio-lopez** [comment]
Jarek OK-ed it. Merging. We can address the Windows issues separately.

**Comment by redgoat650** [comment]
Was unable to reproduce the Windows issue when running the tests locally. The test passes if running in an elevated environment, and fails for something different during setup if not. Didn't dive into the local setup failure. I was able to reproduce an `Access is denied` error by modifying file mode of a test file before issuing `atomic.WriteFile` to overwrite it (the operation that seemed to fail in the CI test). Since the tests run as non-admin in CI, the permissions error may be expected in certain circumstances. As a workaround I've prevented the overwrite test step from running on Windows for now.
