### PR TITLE
repo: deprecated NONE algorithm, will not be available for new repositories

### LINKED ISSUE #388: Remove support for unencrypted repos
Support for the "no encryption" cipher should be disabled in released kopia binaries. It should only be used for testing purposes.

This avoids unintentional and incorrect misuses.

### PR DESCRIPTION
**Pull request by jkowalski**
Fixes #388

### CODE REVIEW

File: internal/repotesting/repotesting.go [hunk 1]
```diff
@@ -48,7 +48,7 @@ func (e *Environment) Setup(t *testing.T, opts ...func(*repo.NewRepositoryOption
 		BlockFormat: content.FormattingOptions{
 			HMACSecret: []byte{},
 			Hash:       "HMAC-SHA256",
-			Encryption: encryption.NoneAlgorithm,
```
Comment (julio-lopez) [inline internal/repotesting/repotesting.go]: Not sure how large of an impact this will have in tests running time.
The initial thinking was to allow this for testing if needed.

File: repo/manifest/manifest_manager_test.go [hunk 2]
```diff
@@ -293,7 +294,7 @@ func newManagerForTesting(ctx context.Context, t *testing.T, data blobtesting.Da
 
 	bm, err := content.NewManager(ctx, st, &content.FormattingOptions{
 		Hash:        "HMAC-SHA256-128",
```
Comment (julio-lopez) [inline repo/manifest/manifest_manager_test.go]: might as well change this for consistency
```suggestion
		Hash:        hashing.DefaultAlgorithm,
```

File: internal/repotesting/repotesting.go (hunk 1 above)
Comment (jkowalski) [reply internal/repotesting/repotesting.go]: if this is too slow we can always go back to unencrypted. I don't see any measurable difference.
